FROM --platform=$TARGETARCH mcr.microsoft.com/dotnet/aspnet:9.0.7 AS base
ARG TARGETARCH
WORKDIR /app
COPY src/ScreenshotCreator.Api/install-powershell-$TARGETARCH.sh /scripts/install-powershell-$TARGETARCH.sh
RUN chmod +x /scripts/install-powershell-$TARGETARCH.sh
RUN /scripts/install-powershell-$TARGETARCH.sh

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0.303 AS sdk
WORKDIR /src_playwright
RUN dotnet new console --no-restore 
RUN dotnet add package Microsoft.Playwright
RUN dotnet build --property:PlaywrightPlatform=all -c Release

FROM base AS playwright-install
COPY --from=sdk /src_playwright/bin/Release/net*/ /src/
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN mkdir /ms-playwright
RUN ["pwsh", "/src/playwright.ps1", "install", "chromium"]
RUN ["pwsh", "/src/playwright.ps1", "install-deps", "chromium"]
RUN mkdir /ms-playwright-driver
RUN mkdir /ms-playwright-driver/.playwright
COPY --from=sdk /src_playwright/bin/Release/net*/.playwright /ms-playwright-driver/.playwright
ENV PLAYWRIGHT_DRIVER_SEARCH_PATH=/ms-playwright-driver
RUN chmod +x /ms-playwright-driver/.playwright/node/*/node
RUN rm -rf /src/*