name: Combined CI / Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow Dispatch and wait
        if: ${{ contains(github.ref, 'renovate/playwright') }}
        uses: aurelien-baudet/workflow-dispatch@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true
          workflow: Playwright

  shared_ci_cd:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    needs: ci_cd

    uses: mu88/common/.github/workflows/ci-cd.yml@f2d2cd5dc094c273ca7b69b2bd08f358e585c93d
    with:
      docker-attest-provenance-and-sbom: true
      docker-publish-project: src/ScreenshotCreator.Api/ScreenshotCreator.Api.csproj
      requires-docker-login: true
      sonar-key: mu88_ScreenshotCreator
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
