name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore ScreenshotCreator.sln
      - name: Build
        run: dotnet build --no-restore ScreenshotCreator.sln
      - name: Test
        run: dotnet test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and push Docker image for Raspberry Pi
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          platforms: linux/arm64,linux/amd64
          tags: |
            mu88/screenshotcreator:latest
            mu88/screenshotcreator:${{ env.VERSION }}
          file: src/ScreenshotCreator.Api/Dockerfile