name: GitHub Actions Checks

on:
  push:
    paths:
      - '.github/**'

jobs:
  gha-checks:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: mu88/common/.github/workflows/gha-checks.yml@88212c6622e513f916ae6f1cedadf83d57e68d08 # main
