name: GitHub Actions Checks

on:
  push:
    paths:
      - '.github/**'

jobs:
  gha-checks:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: mu88/common/.github/workflows/gha-checks.yml@309b9cb3032fc1ca368e5c414baf4998c700e314 # main
